export const PETITION_FEATURED = 'PETITION_FEATURED';
export const PETITION_POPULAR = 'PETITION_POPULAR';
export const PETITION_RECENT = 'PETITION_RECENT';
export const PETITION_VICTORY = 'PETITION_VICTORY';
export const PETITION_ERROR = 'PETITION_ERROR';
export const PETITION_REQUESTED = 'PETITION_REQUESTED';