export const COMMENT_REQUESTS = 'COMMENT_REQUESTS';
export const COMMENT_ADDED = 'COMMENT_ADDED';
export const REMOVED_COMMENTS = 'REMOVED_COMMENTS';
export const REMOVE_ERRORS = 'REMOVED_ERRORS';
export const COMMENT_ERROR = 'COMMENT_ERROR';